<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\JobFlow.Core\JobFlow.Core.csproj" />
    <ProjectReference Include="..\..\src\JobFlow.SqlServer\JobFlow.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\JobFlow.Blazor\JobFlow.Blazor.csproj" />
  </ItemGroup>
</Project>
